name: Deploy to EC2 Staging on PR
on:
  pull_request:
    types:
      - opened

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2-1 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/staging-ssr/astarwebsite_v2
            git stash
            git checkout ${{ github.event.pull_request.head.ref }}
            git pull
            npm ci
            npm run build
            sudo systemctl restart ssr-stage.service
