name: Deploy Strapi to EC2
'on':
  push:
    branches:
      - ecosystem-page

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
           ip a
           cd ~/astarwebsite_v2
           git pull
