name: Astar-Stage-SynctoS3
'on':
  push:
    branches:
      - ecosystem-page
  pull_request:
    branches:
      - ecosystem-page 
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run generate
      - run: ls frontend/.output/public/index.html
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy app build to S3 bucket
        run: aws s3 sync frontend/.output/public/  s3://astar-git.astar.network --delete
